### ISSUE TITLE
Error in further processing because of the value of HEAD in the converted output files. 

### ISSUE THREAD

**Issue by thesagarsehgal** [cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter#10]
When using the `cldiconll2conllu` tool we get to see this warning for a number of files:-
```
Incorrect File Format in file mtaac_gold_corpus/morph/to_dict/P432164.conll for line ... 
```
and the reason for this is when a line in our cdli-conll format file is more than 7( the number of fields in cdli-conll format).

What currently is being done [here](https://github.com/cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter/blob/master/cdliconll2conllu/converter.py#L172) is the index of HEAD i.e. the 5th column (starting count from 0) is being taken directly as the value of HEAD.

When using the `conllu2rdf` converted data for the CONLLU converted data, it gives error ... for because of the HEAD value .... it requires the HEAD value to be an ID ...

**Possible Solution**:-
What I got from observing the data is that the SEGM and the XPOSTAG are being mentioned many times  .... like in [this](https://github.com/cdli-gh/mtaac_gold_corpus/blob/workflow/morph/to_dict/P121886.conll#L21) case. The `lugal[king][-ak][-ø]	N.GEN.ABS` with a bit variations have been mentioned many times. I think we have to search them recursively till the point we get to the HEAD.

But how will I get to know that the SEGM and XPOSTAG have ended? Is HEAD always `_`? I saw the same in most of the files. 
 
Is this process correct? 

@jayanthjaiswal @epageperron

**Comment by epageperron** [comment]
Yes the ID issue is a problem for all tools dealing with Conll-U because our ids are not following conll-u convention.  

There is a cleaner tool that removes all data after the misc column that must be run on the files after using the morphological pre-annotator. We don't expect editors to spend the time manually deleting extra columns. This function can be accessed in the pre-annotator https://github.com/cdli-gh/morphology-pre-annotation-tool   
  
> To just check the format of conll tool, use the --check/-c switch:  

`$ mpat -c -i ./resources`. 
  
> To just run the formattor to format the conll files for next Conll-U convertor, use the --format_conll/-f switch:  
  
`$ mpat -f -i ./resources`.   
  
To know if you are at the head column you have to process the lines with tsv processor (or count the tabs). The head field always in the same column.
